### ISSUE TITLE
Contao 3.3.5

### ISSUE THREAD

**Issue by tniebergall** [baumannsven/metamodels_index_sitemap#4]
Hi,

unter Contao 3.3.5 scheinen die Module nicht zu funktionieren. Das Datenbank update wird nicht ausgeführt und somit das Feld in den Rendersettings nicht angezeigt.

Ich Nutze MetaModels tng Branch.

Ist hier etwas bekannt?

Danke

Gruß Tobias

**Comment by baumannsven** [comment]
Diese Funktionalität wurde in MetaModels intrigiert. Nimm die aktuelle Version von MM.
